import Layout from "../views/layouts/Layout";
import Landing from "../views/Landing";

export default function Home() {
  return (
    <Layout
      main={<Landing />}
      title="Anasayfa"
      description="Generated by create next app"
    />
  );
}
